### ISSUE TITLE
libGLESv2.so doesn't work in raspbian stretch

### ISSUE THREAD

**Issue by anandmg101** [meekys/vol_overlay#1]
Hi,

I'm running into this issue, as outlined in https://www.raspberrypi.org/forums/viewtopic.php?t=191857

`pi@raspberrypi:~/vol_overlay $ sudo python vol_overlay.py
Traceback (most recent call last):
  File "vol_overlay.py", line 3, in <module>
    from display_bcm import Display
  File "/home/pi/vol_overlay/display_bcm.py", line 21, in <module>
    cdll.LoadLibrary("/opt/vc/lib/libGLESv2.so")
  File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /opt/vc/lib/libGLESv2.so: cannot open shared object file: No such file or directory`

Any easy fix for this?

**Comment by meekys** [comment]
You could try changing the **libGLESv2.so** to **libbrcmGLESv2.so** on this line?
https://github.com/meekys/vol_overlay/blob/master/display_bcm.py#L21

If that isn't enough, you could try changing **lib%s.so** to **libbrcm%s.so** on this line too?
https://github.com/meekys/vol_overlay/blob/master/display_bcm.py#L11

**Comment by anandmg101** [comment]
Hey meekys, this worked thanks! I will close this one but I have another question so will open another one
